### PR TITLE
DNS Server Monitor Resource

### PR DESCRIPTION
**Pull request by graham-russell**
Thank you for providing a Site24x7 Terraform provider.

This PR adds the DNS Server monitor resource. (https://www.site24x7.com/help/api/#dns-server) Data source will be submitted in a separate PR.

Includes:
## site24x7_dns_server_monitor resource
Created api.DNSServerMonitor struct for this which uses api.SearchConfig struct for search_config parameter (https://www.site24x7.com/help/api/#dns_search_config) Have updated the relevant terraform resource files to implement this.

## Tests
Added dns_server_impl_test.go, client_test.go and dns_server_test.go for testing the resource.

## Coverage
Ran `make coverage` to update coverage.txt to cover new dns server monitor resource.

## Documentation Updated relevant documentation to make reference to new resource. Fixed monitor_group_test.go In func TestMonitorGroupCreate, tests were failing with:
```
--- Expected
+++ Actual
@@ -4,3 +4,3 @@
   Description: "baz",
-  HealthThresholdCount: 0,
+  HealthThresholdCount: 1,
   DependencyResourceIDs: ["234","567"],
```
I've added HealthThresholdCount:1, to var a (L24) and tests are now passing.

### CODE REVIEW

**Comment by graham-russell** [comment]
Tagging @jim-billy-zoho for visibility.

**Review by jim-billy — APPROVED** [review]

**Review by jim-billy — APPROVED** [review]

**Review by jim-billy-zoho — APPROVED** [review]

**Comment by jim-billy-zoho** [comment]
@graham-russell  Thank you for your contribution.

**Comment by graham-russell** [comment]
Thanks for the review @jim-billy / @jim-billy-zoho - Could you publish the latest version to the Terraform Registry when you have a chance?

**Comment by jim-billy-zoho** [comment]
> Thanks for the review @jim-billy / @jim-billy-zoho - Could you publish the latest version to the Terraform Registry when you have a chance?

We are looking into the issue @graham-russell . Sorry for the inconvenience.

**Comment by jim-billy-zoho** [comment]
> > Thanks for the review @jim-billy / @jim-billy-zoho - Could you publish the latest version to the Terraform Registry when you have a chance?
> 
> We are looking into the issue @graham-russell . Sorry for the inconvenience.

@graham-russell There was some syncing issue in terraform registry and they have updated the latest version to 1.0.47 now.

**Pull request merged**
